language: node_js

sudo: required

services:
  - docker
before_install:
  - sudo apt-get install jq
  - git clone https://github.com/evannetwork/testcore-config.git
  - docker run -d -p 8546:8546 -p 8545:8545 --name testcore-snapshot parity/parity:stable --chain evantestcore --jsonrpc-interface all --unsafe-expose --tracing on --pruning=archive
  - export CC="gcc-5" && export CXX="g++-5" && export LINK="gcc-5" && export LINKXX="g++-5"

script:
  - sleep 100
  - ./syncWatch.sh
  - docker commit testcore-snapshot evannetwork/testcore-snapshot

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push evannetwork/testcore-snapshot

